# Generated by Django 4.2.2 on 2023-06-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_and_plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ('id',)},
        ),
    ]
