# Generated by Django 4.2.2 on 2023-06-14 19:21

import django.core.validators
from django.db import migrations, models
import musicAppProject.album.utils


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_alter_album_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='price',
            field=models.FloatField(validators=[musicAppProject.album.utils.floor_float_number, django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
