version: '3.4'

services:
  web:
    image: ramun3/my_plant_app
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./envs/.env
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Kristiyan94
      POSTGRES_USER: ramune
      POSTGRES_DB: MyplantsDB
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data

